### ISSUE TITLE
Missing License

### ISSUE THREAD

**Issue by hbonath** [iXsystems/cinder#10]
I noticed that this project is missing a License, and I don't want to assume anything.

I would like to add this to PyPi for easier integration with Openstack Deployment methods, but wanted to first make sure that I had permission to do so.

Thanks!

**Comment by william-gr** [comment]
@hbonath Hello! Thanks for asking. I have added a LICENSE now.

However we would prefer to upload to pypi ourselves if you don't mind.

We just need instructions of what exactly needs to be uploaded. Does it need to be a full python package to be imported, or just a zip of the contents?

**Comment by hbonath** [comment]
Thanks for getting the license in there, and for offering to maintain the packaging aspects.

TBH, I'm not sure exactly how things are packaged within PyPi exactly and was initially planning on experimenting to that effect.

Ideally I would like to be able to do is something like a "pip install ixsystems-cinder" and have the driver install into the correct location. e.g. `$CINDER_HOME/cinder/volume/drivers/`**ixsystems** 
For Devstack this would be `/opt/stack/cinder/cinder/volume/drivers/`**ixsystems**

I know that with Openstack-Ansible for example, additional pip packages can be installed via the automated deployment, and I would assume this to be true for some of the other deployment methods.

**Comment by YiHuangIX** [comment]
Hi hbonath, I am closing this issue since license file is updated here: https://github.com/iXsystems/cinder/blob/master/LICENSE
For your suggestions to create a pypi package for ixsystem-cinder driver for easy installation, I've created a task in backlog and once progress has been made on it you should see it from master branch.
