### ISSUE TITLE
Juju charm needed as any changes I make to cinder.conf are replaced

### ISSUE THREAD

**Issue by leijonatm** [iXsystems/cinder#38]
Tried to follow https://docs.openstack.org/charm-guide/latest/community/software-contrib/new-cinder-driver-charm.html but am a newbie in programming and everything went south. 
Could we be provided with a charm and instructions on how to use it ?

Thanks

**Comment by databunnysg** [comment]
Hi, I've a charmed Truenas driver created here, https://github.com/databunnysg/cinder-databunny-driver, however it is not updated with latest https://github.com/iXsystems/cinder master branch code. I've limited bandwidth to update it as for now, you can fork it and update it if you need it urgently.

**Comment by leijonatm** [comment]
Thanks so much @databunnysg for your reply. How back is it comparing to the latest release of the cinder branch code ? I would love to do it my self although my knowledge is programming is limited to like scripting ... I can work with the one you have ready and maybe you could reply to this thread once you have it ready ? or how could I do it myself ?

Don't know what works best for you ...

**Comment by databunnysg** [comment]
https://github.com/databunnysg/cinder-databunny-driver is around 9 months behind https://github.com/iXsystems/cinder master branch, it already supports Truenas scale on Truenas api 2.0, missing a few patches after that. If you are interested and want invest a bit to charm dev, you can take a look at the code and update it. I may not update it in 2-3 months time minimal. BTW are you running production workload on your juju openstack Truenas deployment or experiment deployment?

**Comment by leijonatm** [comment]
Thanks again for your reply @databunnysg. I am deploying a new infra for our production load. 
I will look at the code although I am more into systems engineering rather than developer.

**Comment by databunnysg** [comment]
For production openstack work load, I recommend to use https://github.com/iXsystems/cinder master branch code, there are quite some important patches included since last time https://github.com/databunnysg/cinder-databunny-driver was build.

**Comment by leijonatm** [comment]
Hello @databunnysg,
dropped a comment here if you plan to update your code as well , or comment when you done it please. 

Regards
