### ISSUE TITLE
cinder feature retype not implemented

### ISSUE THREAD

**Issue by databunnysg** [iXsystems/cinder#43]
cinder driver feature retype not implemented failed test_volume_crud_with_volume_type_and_extra_specs tempest ci test case
https://docs.openstack.org/tempest/latest/_modules/volume/admin/test_volume_types.html#VolumeTypesTest.test_volume_crud_with_volume_type_and_extra_specs

**Comment by YiHuangDB** [comment]
I am closing this one, this failed test case was able run successfully with latest PR #44 .
